#!/bin/bash
cpu=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}')
cpu_temp=$(sensors | grep "Core 0" | awk '{print $3}')
ram=$(free -h | awk '/Mem:/ {print $3"/"$2}')
gpu=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)
gpu_temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)

echo "CPU: ${cpu}% ${cpu_temp}\nRAM: ${ram}\nGPU: ${gpu}% ${gpu_temp}°C"
